### ISSUE TITLE
code/design review - Saif en Jules

### ISSUE THREAD

**Issue by julesbruins** [Karima002/all-human-accessible-websites-#2]
- Is dit de juiste alt attribute? Heeft een blind iemand bijvoorbeeld echt wat aan deze beschrijving? https://github.com/Karima002/all-human-accessible-websites-/blob/5e78a2abd48ad64d75147349e21873c3c934cbca/index.html#L172
- typ fout? https://github.com/Karima002/all-human-accessible-websites-/blob/5e78a2abd48ad64d75147349e21873c3c934cbca/index.html#L119

W3C validator:
- geen [h3] in een [ul] element. Zet hem er ff boven. 
- pas de language aan naar NL, omdat het document in Nederlands geschreven is ook. 
- Elke section moet een heading hebben, check ze allemaal even. https://github.com/Karima002/all-human-accessible-websites-/blob/5e78a2abd48ad64d75147349e21873c3c934cbca/index.html#L33

- headings doe je goed!
- Je hebt het verschil tussen <a> en <button> goed door. 
- tabs doe je goed!

**Comment by Karima002** [comment]
Commit:

- Aanpassen van alt attribute van images
- Aanpassen van `h2` in `h3`
- Aanpassen van taal naar nederlands
